import{i as L}from"./assets/vendor-59215b7c.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();function m(t){return t.map(({comments:s,downloads:i,largeImageURL:a,likes:e,webformatURL:o,tags:c,views:b})=>`<li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${o}" alt="${c}">
          <ul class="gallery-item-description">
            <li>Likes: ${e}</li>
            <li>Views: ${b}</li>
            <li>Downloads: ${i}</li>
            <li>Comments: ${s}</li>
          </ul>
        </a>
      </li>`).join("")}const M="https://pixabay.com/api/",v="41864490-ab1aa9c4772cfd6b871252eca";function h({query:t,page:s=1,per_page:i}){return axios.get(`${M}?key=${v}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&`,{params:{per_page:i,page:s}}).then(({data:a})=>a)}const w="/goit-js-hw-12/assets/error-5b075f14.svg";function d(t=""){const s=t||"Sorry, there was an error fetching images.";L.show({iconUrl:w,theme:"dark",message:s,messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",timeout:5e3})}const f=document.querySelector(".loader");function g(){setTimeout(()=>{f.style.display="none"},500)}function y(){f.style.display="block"}function p(){window.scrollBy({top:2*document.querySelector(".gallery-item").getBoundingClientRect().height,behavior:"smooth"})}const r={searchForm:document.querySelector(".search-form"),imageList:document.querySelector(".gallery"),btnMore:document.querySelector(".load-btn")},n={query:"",page:1,maxPage:0,per_page:40},l="is-hidden";r.searchForm.addEventListener("submit",q);async function q(t){t.preventDefault(),r.imageList.innerHTML="",n.page=1;const s=t.currentTarget;if(n.query=s.elements.query.value.trim(),y(),!!n.query)try{const{hits:i,totalHits:a}=await h(n);n.maxPage=Math.ceil(a/n.per_page),r.imageList.insertAdjacentHTML("beforeend",m(i)),i.length===0?(d("Sorry, there are no images matching your search query. Please, try again!"),r.btnMore.classList.add(l)):i.length>0&&i.length!==a?(r.btnMore.classList.remove(l),r.btnMore.addEventListener("click",u)):(r.btnMore.classList.add(l),d("We're sorry, but you've reached the end of search results."))}catch{d("Sorry, there is a problem with connection with the server.")}finally{g(),s.reset(),p()}}async function u(){n.page+=1,y(),r.btnMore.disabled=!0;try{const{hits:t}=await h(n);r.imageList.insertAdjacentHTML("beforeend",m(t)),t.length>0?(r.btnMore.classList.remove(l),r.btnMore.addEventListener("click",u)):(r.btnMore.classList.add(l),d("We're sorry, but you've reached the end of search results."))}catch(t){handleError(t)}finally{g(),r.btnMore.disabled=!1,n.page===n.maxPage&&(r.btnMore.classList.add(l),r.btnMore.removeEventListener("click",u)),p(),gallery.refresh()}}
//# sourceMappingURL=commonHelpers.js.map
